//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aufbauwerk.Surfstation.Server.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0.0.0")]
        public string RadiusAddress {
            get {
                return ((string)(this["RadiusAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1812")]
        public int RadiusPort {
            get {
                return ((int)(this["RadiusPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<secret>")]
        public string RadiusSecret {
            get {
                return ((string)(this["RadiusSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 225")]
        public global::System.Drawing.Size ScreenshotSize {
            get {
                return ((global::System.Drawing.Size)(this["ScreenshotSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Format24bppRgb")]
        public global::System.Drawing.Imaging.PixelFormat ScreenshotFormat {
            get {
                return ((global::System.Drawing.Imaging.PixelFormat)(this["ScreenshotFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:10:00")]
        public global::System.TimeSpan ScreenshotCleanupInterval {
            get {
                return ((global::System.TimeSpan)(this["ScreenshotCleanupInterval"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT [ID], [Typ] AS [State], [Timeout] FROM [Internetzugang] WHERE [Username] =" +
            " @UserName AND [Passwort] = @Password")]
        public string CommandInitialLogin {
            get {
                return ((string)(this["CommandInitialLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) > 0 FROM [Internetzugang] WHERE [ID] = @ID AND [Typ] = @State")]
        public string CommandVerifyLogin {
            get {
                return ((string)(this["CommandVerifyLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO [Internet](ID,Typ,Dauer,Adresse) VALUES(@ID,@State,@Duration,@Client)" +
            "")]
        public string CommandCreateSession {
            get {
                return ((string)(this["CommandCreateSession"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE [Internet] SET [Dauer] = @Duration WHERE [Sitzung] = @Session")]
        public string CommandUpdateDuration {
            get {
                return ((string)(this["CommandUpdateDuration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE [Internet] SET [Screenshot] = @Screenshot WHERE [Sitzung] = @Session")]
        public string CommandUpdateScreenshot {
            get {
                return ((string)(this["CommandUpdateScreenshot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE [Internet] SET [Screenshot] = NULL WHERE DateAdd(\'s\',[Dauer],[Zeit]) < Dat" +
            "eAdd(\'s\',-@Interval,Now())")]
        public string CommandCleanupScreenshots {
            get {
                return ((string)(this["CommandCleanupScreenshots"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=.\\Lehrlinge.mdb;OLE DB Services=-1")]
        public string Database {
            get {
                return ((string)(this["Database"]));
            }
        }
    }
}
